version: '3.4'

services:
  postgres:
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=users;User Id=postgres;Password=postgrespass
      - TokenKey=MEgCQQCPbDhohZXk+x+qmz7M49VenP4YsAmNdkNeHlLaeKY3oXRZxmVHePw006+U54VubXfshn7izM4mujXE48x9py/zAgMBAAE=
    ports:
      - 6003:8080
